version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./webrota-api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  # python:
  #   build:
  #     context: ./webrota-api
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - db
  #   ports:
  #     - "5000:5000"

  web:
    build:
      context: ./webrota-front
    volumes:
      - ./webrota-web:/webrota-web
    ports:
      - "4200:4200"
